application: regexworks
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: js

- url: /lib
  static_dir: lib

- url: /css
  static_dir: css

- url: /.*
  script: app.app
